<?php 
use Kazinduzi\Core\Kazinduzi;
?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title><?php echo $this->title . ' - ' . Kazinduzi::getAppName(); ?></title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width">
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<link rel="stylesheet" type="text/css" href="/html/css/cke_filemanager.css" media="all">
	<link rel="stylesheet" href="/html/font-awesome/css/font-awesome.min.css">
    </head>
    <body>
	<div id="container">
	    <div id="menu">
		<a id="create" class="btn create"><?php echo $button_folder; ?></a>
		<a id="delete" class="btn delete"><?php echo $button_delete; ?></a>
		<a id="move" class="btn move"><?php echo $button_move; ?></a>
		<a id="copy" class="btn copy"><?php echo $button_copy; ?></a>
		<a id="rename" class="btn rename"><?php echo $button_rename; ?></a>
		<a id="upload" class="btn upload"><?php echo $button_upload; ?></a>
		<a id="refresh" class="btn refresh"><?php echo $button_refresh; ?></a>
	    </div>
	    <div id="column-left"></div>
	    <div id="column-right"></div>
	</div>
	<link rel="stylesheet" type="text/css" href="/html/js/jquery/ui/jquery-ui.min.css" />
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script type="text/javascript" src="/html/js/jquery/ui/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/html/js/jquery/ui/external/jquery.bgiframe.js"></script>
	<script type="text/javascript" src="/html/js/jquery/jstree/jquery.tree.min.js"></script>
	<script type="text/javascript" src="/html/js/jquery/ajaxupload.js"></script>
	<script type="text/javascript">
            /*<![CDATA[*/
            $(document).ready(function () {
                (function () {
                    var special = jQuery.event.special,
                            uid1 = 'D' + (+new Date()),
                            uid2 = 'D' + (+new Date() + 1);

                    special.scrollstart = {
                        setup: function () {
                            var timer,
                                    handler = function (evt) {
                                        var _self = this,
                                                _args = arguments;

                                        if (timer) {
                                            clearTimeout(timer);
                                        } else {
                                            evt.type = 'scrollstart';
                                            jQuery.event.handle.apply(_self, _args);
                                        }
                                        timer = setTimeout(function () {
                                            timer = null;
                                        }, special.scrollstop.latency);
                                    };
                            jQuery(this).bind('scroll', handler).data(uid1, handler);
                        },
                        teardown: function () {
                            jQuery(this).unbind('scroll', jQuery(this).data(uid1));
                        }
                    };

                    special.scrollstop = {
                        latency: 300,
                        setup: function () {

                            var timer,
                                    handler = function (evt) {
                                        var _self = this,
                                                _args = arguments;

                                        if (timer) {
                                            clearTimeout(timer);
                                        }

                                        timer = setTimeout(function () {
                                            timer = null;
                                            evt.type = 'scrollstop';
                                            jQuery.event.handle.apply(_self, _args);
                                        }, special.scrollstop.latency);
                                    };

                            jQuery(this).bind('scroll', handler).data(uid2, handler);

                        },
                        teardown: function () {
                            jQuery(this).unbind('scroll', jQuery(this).data(uid2));
                        }
                    };
                })();

                $('#column-left').tree({
                    data: {
                        type: 'json',
                        async: true,
                        opts: {
                            method: 'POST',
                            url: '/filemanager/directory?type=<?php echo $type; ?>&token=<?php echo $token; ?>'
                        }
                    },
                    selected: 'top',
                    ui: {
                        theme_name: 'classic',
                        animation: 700
                    },
                    types: {
                        'default': {
                            clickable: true,
                            creatable: false,
                            renameable: false,
                            deletable: false,
                            draggable: false,
                            max_children: -1,
                            max_depth: -1,
                            valid_children: 'all'
                        }
                    },
                    callback: {
                        beforedata: function (NODE, TREE_OBJ) {
                            if (NODE == false) {
                                TREE_OBJ.settings.data.opts.static = [
                                    {
                                        data: '<?php echo $directory; ?>',
                                        attributes: {
                                            'id': 'top',
                                            'directory': ''
                                        },
                                        state: 'closed'
                                    }
                                ];

                                return {'directory': ''}
                            } else {
                                TREE_OBJ.settings.data.opts.static = false;

                                return {'directory': $(NODE).attr('directory')}
                            }
                        },
                        onselect: function (NODE, TREE_OBJ) {
                            $.ajax({
                                url: '/filemanager/files?type=<?php echo $type; ?>&token=<?php echo $token; ?>',
                                type: 'POST',
                                data: 'directory=' + encodeURIComponent($(NODE).attr('directory')),
                                dataType: 'json',
                                success: function (json) {
                                    html = '<div>';
                                    if (json) {
                                        for (i = 0; i < json.length; i++) {
                                            name = '';
                                            filename = json[i]['filename'];
                                            for (j = 0; j < filename.length; j = j + 15) {
                                                name += filename.substr(j, 15) + '<br />';
                                            }
                                            name += json[i]['size'];
                                            html += '<a file="' + json[i]['file'] + '"><img src="' + json[i]['thumb'] + '" title="' + json[i]['filename'] + '" /><br />' + name + '</a>';
                                        }
                                    }
                                    html += '</div>';
                                    $('#column-right').html(html);
                                }
                            });
                        }
                    }
                });

                $('#column-right a').live('click', function () {
                    if ($(this).attr('class') == 'selected') {
                        $(this).removeAttr('class');
                    } else {
                        $('#column-right a').removeAttr('class');
                        $(this).attr('class', 'selected');
                    }
                });

                $('#column-right a').live('dblclick', function () {
<?php if ($fckeditor) : ?>
                        window.opener.CKEDITOR.tools.callFunction(<?php echo $fckeditor; ?>, '<?php echo $directory; ?>' + $(this).attr('file'));
                        self.close();
<?php else : ?>
                        parent.$('#<?php echo $field; ?>').attr('value', '<?php echo $directory; ?>' + $(this).attr('file'));
                        parent.$('#dialog').dialog('close');
                        parent.$('#dialog').remove();
<?php endif; ?>
                });

                $('#create').bind('click', function () {
                    var tree = $.tree.focused();
                    if (tree.selected) {
                        $('#dialog').remove();
                        html = '<div id="dialog">';
                        html += '<?php echo $entry_folder; ?> <input type="text" name="name" value="" /> <input type="button" value="Submit" />';
                        html += '</div>';
                        $('#column-right').prepend(html);
                        $('#dialog').dialog({
                            title: '<?php echo $button_folder; ?>',
                            resizable: false
                        });

                        $('#dialog input[type="button"]').bind('click', function () {
                            $.ajax({
                                url: '/filemanager/create?type=<?php echo $type; ?>&token=<?php echo $token; ?>',
                                type: 'POST',
                                data: 'directory=' + encodeURIComponent($(tree.selected).attr('directory')) + '&name=' + encodeURIComponent($('#dialog input[name="name"]').val()),
                                dataType: 'json',
                                success: function (json) {
                                    if (json.success) {
                                        $('#dialog').remove();
                                        tree.refresh(tree.selected);
                                        alert(json.success);
                                    } else {
                                        alert(json.error);
                                    }
                                }
                            });
                        });
                    } else {
                        alert('<?php echo $error_directory; ?>');
                    }
                });

                $('#delete').bind('click', function () {
                    path = $('#column-right a.selected').attr('file');
                    if (path) {
                        $.ajax({
                            url: '/filemanager/delete?type=<?php echo $type; ?>&token=<?php echo $token; ?>',
                            type: 'POST',
                            data: 'path=' + path,
                            dataType: 'json',
                            success: function (json) {
                                if (json.success) {
                                    var tree = $.tree.focused();
                                    tree.select_branch(tree.selected);
                                    alert(json.success);
                                }
                                if (json.error) {
                                    alert(json.error);
                                }
                            }
                        });
                    } else {
                        var tree = $.tree.focused();
                        if (tree.selected) {
                            $.ajax({
                                url: '/filemanager/delete?type=<?php echo $type; ?>&token=<?php echo $token; ?>',
                                type: 'POST',
                                data: 'path=' + encodeURIComponent($(tree.selected).attr('directory')),
                                dataType: 'json',
                                success: function (json) {
                                    if (json.success) {
                                        tree.select_branch(tree.parent(tree.selected));
                                        tree.refresh(tree.selected);
                                        alert(json.success);
                                    }
                                    if (json.error) {
                                        alert(json.error);
                                    }
                                }
                            });
                        } else {
                            alert('<?php echo $error_select; ?>');
                        }
                    }
                });

                $('#move').bind('click', function () {
                    $('#dialog').remove();
                    html = '<div id="dialog">';
                    html += '<?php echo $entry_move; ?> <select name="to"></select> <input type="button" value="Submit" />';
                    html += '</div>';
                    $('#column-right').prepend(html);
                    $('#dialog').dialog({
                        title: '<?php echo $button_move; ?>',
                        resizable: false
                    });

                    $('#dialog select[name="to"]').load('/filemanager/folders?type=<?php echo $type; ?>&token=<?php echo $token; ?>');

                    $('#dialog input[type="button"]').bind('click', function () {
                        path = $('#column-right a.selected').attr('file');
                        if (path) {
                            $.ajax({
                                url: '/filemanager/move?token=<?php echo $token; ?>',
                                type: 'POST',
                                data: 'from=' + encodeURIComponent(path) + '&to=' + encodeURIComponent($('#dialog select[name="to"]').val()),
                                dataType: 'json',
                                success: function (json) {
                                    if (json.success) {
                                        $('#dialog').remove();
                                        var tree = $.tree.focused();
                                        tree.select_branch(tree.selected);
                                        alert(json.success);
                                    }
                                    if (json.error) {
                                        alert(json.error);
                                    }
                                }
                            });
                        } else {
                            var tree = $.tree.focused();
                            $.ajax({
                                url: '/filemanager/move?type=<?php echo $type; ?>&token=<?php echo $token; ?>',
                                type: 'POST',
                                data: 'from=' + encodeURIComponent($(tree.selected).attr('directory')) + '&to=' + encodeURIComponent($('#dialog select[name="to"]').val()),
                                dataType: 'json',
                                success: function (json) {
                                    if (json.success) {
                                        $('#dialog').remove();
                                        tree.select_branch('#top');
                                        tree.refresh(tree.selected);
                                        alert(json.success);
                                    }
                                    if (json.error) {
                                        alert(json.error);
                                    }
                                }
                            });
                        }
                    });
                });

                $('#copy').bind('click', function () {
                    $('#dialog').remove();
                    html = '<div id="dialog">';
                    html += '<?php echo $entry_copy; ?> <input type="text" name="name" value="" /> <input type="button" value="Submit" />';
                    html += '</div>';
                    $('#column-right').prepend(html);
                    $('#dialog').dialog({
                        title: '<?php echo $button_copy; ?>',
                        resizable: false
                    });
                    $('#dialog select[name="to"]').load('/filemanager/folders?type=<?php echo $type; ?>&token=<?php echo $token; ?>');

                    $('#dialog input[type="button"]').bind('click', function () {
                        path = $('#column-right a.selected').attr('file');
                        if (path) {
                            $.ajax({
                                url: '/filemanager/copy?type=<?php echo $type; ?>&token=<?php echo $token; ?>',
                                type: 'POST',
                                data: 'path=' + encodeURIComponent(path) + '&name=' + encodeURIComponent($('#dialog input[name="name"]').val()),
                                dataType: 'json',
                                success: function (json) {
                                    if (json.success) {
                                        $('#dialog').remove();
                                        var tree = $.tree.focused();
                                        tree.select_branch(tree.selected);
                                        alert(json.success);
                                    }
                                    if (json.error) {
                                        alert(json.error);
                                    }
                                }
                            });
                        } else {
                            var tree = $.tree.focused();
                            $.ajax({
                                url: '/filemanager/copy?type=<?php echo $type; ?>&token=<?php echo $token; ?>',
                                type: 'POST',
                                data: 'path=' + encodeURIComponent($(tree.selected).attr('directory')) + '&name=' + encodeURIComponent($('#dialog input[name="name"]').val()),
                                dataType: 'json',
                                success: function (json) {
                                    if (json.success) {
                                        $('#dialog').remove();
                                        tree.select_branch(tree.parent(tree.selected));
                                        tree.refresh(tree.selected);
                                        alert(json.success);
                                    }
                                    if (json.error) {
                                        alert(json.error);
                                    }
                                }
                            });
                        }
                    });
                });

                $('#rename').bind('click', function () {
                    $('#dialog').remove();
                    html = '<div id="dialog">';
                    html += '<?php echo $entry_rename; ?> <input type="text" name="name" value="" /> <input type="button" value="Submit" />';
                    html += '</div>';

                    $('#column-right').prepend(html);

                    $('#dialog').dialog({
                        title: '<?php echo $button_rename; ?>',
                        resizable: false
                    });

                    $('#dialog input[type="button"]').bind('click', function () {
                        path = $('#column-right a.selected').attr('file');
                        if (path) {
                            $.ajax({
                                url: '/filemanager/rename?type=<?php echo $type; ?>&token=<?php echo $token; ?>',
                                type: 'POST',
                                data: 'path=' + encodeURIComponent(path) + '&name=' + encodeURIComponent($('#dialog input[name="name"]').val()),
                                dataType: 'json',
                                success: function (json) {
                                    if (json.success) {
                                        $('#dialog').remove();
                                        var tree = $.tree.focused();
                                        tree.select_branch(tree.selected);
                                        alert(json.success);
                                    }
                                    if (json.error) {
                                        alert(json.error);
                                    }
                                }
                            });
                        } else {
                            var tree = $.tree.focused();

                            $.ajax({
                                url: '/filemanager/rename?type=<?php echo $type; ?>&token=<?php echo $token; ?>',
                                type: 'POST',
                                data: 'path=' + encodeURIComponent($(tree.selected).attr('directory')) + '&name=' + encodeURIComponent($('#dialog input[name="name"]').val()),
                                dataType: 'json',
                                success: function (json) {
                                    if (json.success) {
                                        $('#dialog').remove();
                                        tree.select_branch(tree.parent(tree.selected));
                                        tree.refresh(tree.selected);
                                        alert(json.success);
                                    }
                                    if (json.error) {
                                        alert(json.error);
                                    }
                                }
                            });
                        }
                    });
                });

                new AjaxUpload('#upload', {
                    action: '/filemanager/upload?type=<?php echo $type; ?>&token=<?php echo $token; ?>',
                    name: 'image',
                    autoSubmit: false,
                    responseType: 'json',
                    onChange: function (file, extension) {
                        var tree = $.tree.focused();
                        if (tree.selected) {
                            this.setData({'directory': $(tree.selected).attr('directory')});
                        } else {
                            this.setData({'directory': ''});
                        }

                        this.submit();
                    },
                    onSubmit: function (file, extension) {
                        $('#upload').append('<img src="/html/js/image/loading.gif" id="loading" style="padding-left: 5px;" />');
                    },
                    onComplete: function (file, json) {
                        if (json.success) {
                            var tree = $.tree.focused();
                            tree.select_branch(tree.selected);
                            alert(json.success);
                        }
                        if (json.error) {
                            alert(json.error);
                        }
                        $('#loading').remove();
                    }
                });

                $('#refresh').bind('click', function () {
                    var tree = $.tree.focused();
                    tree.refresh(tree.selected);
                });
            });
            /*]]>*/
	</script>
    </body>
</html>