<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=8" />
    <meta name="description" content="Kazinduzi - Open Source MVC framework coded in PHP"/>
    <meta name="generator" content="Kazinduzi - open source web application framework" />
    <meta name="robots" content="all" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>    
    <title><?php echo ucfirst($title .' - '. Kazinduzi\Core\Kazinduzi::getAppName())?></title>
</head>
<body>
    <div id="main-holder" class="clearfix">
        <?php echo $content_for_layout ?>
    </div>  
</body>
</html>